<?php
/**
 * Migration: Add Membership Columns to Households Table
 * 
 * This script adds three new optional columns to support membership tracking:
 * - membership_date: Date the membership was established
 * - membership_or_no: Official OR/Invoice number for membership
 * - membership_fee: Amount paid for membership (one-time, optional)
 * 
 * Safe to run multiple times; will skip if columns already exist.
 */

require_once __DIR__ . '/../db.php';

try {
    echo "<h2>Beverly HOA Database Migration: Add Membership Columns</h2>";
    echo "<hr>";
    
    // Check if columns already exist
    $checkStmt = $pdo->prepare("
        SELECT COLUMN_NAME 
        FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA = ? 
        AND TABLE_NAME = 'households' 
        AND COLUMN_NAME IN ('membership_date', 'membership_or_no', 'membership_fee')
    ");
    $checkStmt->execute(['beverly']);
    $existingColumns = $checkStmt->fetchAll(PDO::FETCH_COLUMN);
    
    $columnsToAdd = [
        'membership_date' => "DATE NULL COMMENT 'Date of membership (optional)'",
        'membership_or_no' => "VARCHAR(50) NULL COMMENT 'Membership OR/INV no. (optional)'",
        'membership_fee' => "DECIMAL(10,2) NULL COMMENT 'Membership fee (optional)'"
    ];
    
    $allExist = count($existingColumns) === 3;
    
    if ($allExist) {
        echo "<p style='color: green; font-weight: bold;'>✓ All membership columns already exist. No changes needed.</p>";
    } else {
        // Add missing columns
        $columnsAdded = [];
        foreach ($columnsToAdd as $colName => $colDef) {
            if (in_array($colName, $existingColumns)) {
                echo "<p style='color: orange;'>⊘ Column <strong>$colName</strong> already exists. Skipping.</p>";
            } else {
                $alterSql = "ALTER TABLE households ADD COLUMN $colName $colDef";
                $pdo->exec($alterSql);
                $columnsAdded[] = $colName;
                echo "<p style='color: green;'>✓ Added column: <strong>$colName</strong></p>";
            }
        }
        
        if (empty($columnsAdded)) {
            echo "<p style='color: green; font-weight: bold;'>All membership columns already exist in the database.</p>";
        }
    }
    
    // Verify final state
    echo "<h3>Verification</h3>";
    $verifyStmt = $pdo->query("
        SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE
        FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA = 'beverly' 
        AND TABLE_NAME = 'households' 
        AND COLUMN_NAME IN ('membership_date', 'membership_or_no', 'membership_fee')
        ORDER BY ORDINAL_POSITION
    ");
    $verifyResults = $verifyStmt->fetchAll();
    
    if (count($verifyResults) === 3) {
        echo "<table border='1' cellpadding='10' style='border-collapse: collapse;'>";
        echo "<tr style='background-color: #f0f0f0;'>";
        echo "<th>Column Name</th><th>Type</th><th>Nullable</th>";
        echo "</tr>";
        foreach ($verifyResults as $col) {
            echo "<tr>";
            echo "<td>" . htmlspecialchars($col['COLUMN_NAME']) . "</td>";
            echo "<td>" . htmlspecialchars($col['COLUMN_TYPE']) . "</td>";
            echo "<td>" . htmlspecialchars($col['IS_NULLABLE']) . "</td>";
            echo "</tr>";
        }
        echo "</table>";
        echo "<p style='color: green; font-weight: bold; margin-top: 20px;'>✓✓✓ Migration completed successfully!</p>";
    } else {
        echo "<p style='color: red; font-weight: bold;'>⚠ Verification failed. Expected 3 columns, found " . count($verifyResults) . ".</p>";
    }
    
} catch (Exception $e) {
    echo "<p style='color: red; font-weight: bold;'>Error: " . htmlspecialchars($e->getMessage()) . "</p>";
    die;
}
?>
<!DOCTYPE html>
<html>
<head>
    <title>Beverly HOA - Database Migration</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            background-color: #f9f9f9;
        }
        h2 { color: #2d5016; }
        h3 { color: #333; margin-top: 30px; }
        table { margin-top: 20px; }
        p { line-height: 1.6; }
        hr { margin: 20px 0; }
    </style>
</head>
<body>
<!-- Output generated by PHP above -->
</body>
</html>
